# Generated by Django 2.1.7 on 2019-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_feedbackuserip'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackuserip',
            name='requests',
            field=models.IntegerField(default=0),
        ),
    ]
